#### What is NumPy?

It stands for "Numerical Python". NumPy is a Python module that provides fast and efficient array operations of homogeneous data. The central feature of NumPy is the array object class, also called the ndarray. Arrays are very similar to lists in Python, except that every element of an array must be of the same type (in lists you can hold data which have different types), typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

#### Creating NumPy arrays

The syntax of creating a NumPy array is:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

Here, the arguments

    object: Any object exposing the array interface
    dtype: Desired data type of array, optional
    copy: Optional. By default (true), the object is copied
    order: C (row major) or F (column major) or A (any) (default)
    subok: By default, returned array forced to be a base class array. If true, sub-classes passed through
    ndim: Specifies minimum dimensions of resultant array


In [1]:
#importing numpy library
import numpy as np

In [2]:
#creating 1D array
a = np.array([1,2,3,4])
#creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


### Attributes of numpy arrays

In [3]:
# Shape: returns a tuple consisting of array dimensions
print(a.shape)
print(b.shape)

(4,)
(2, 4)


In [4]:
#dimension: returns a number that describes no of dimesions of array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#Size: total number of items in the array
print(a.size)
print(b.size)

4
8


In [6]:
#Datatype: name of the datatype that is stored in array
print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
#itemsize: the memory consumed by the array
print(a.itemsize)
print(b.itemsize)

4
4


In [8]:
#creating an array of 1st 10 natural numbers
#please note arange function of numpy is similar to range function in python
#arange(startpoint=0, endpoint, increment=1)
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Changing the shape of the array, basically changing the dimension of the array
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
lst = [1,2.3, "abc", True]
y = np.array(lst)
print(y)

['1' '2.3' 'abc' 'True']


### Techniques of creating arrays

In [11]:
#1. creating an empty array
a1 = np.empty((3,2), dtype='int32')
print("a1:" ,a1)


a1: [[0 0]
 [0 0]
 [0 0]]


In [12]:
# creating an array with all zeroes
a2 = np.zeros((3,4), dtype='int32')
print("a2:" ,a2)


a2: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
#creating an array with all ones
a3 = np.ones((2,4), dtype="int32")
print("a3:" ,a3)

a3: [[1 1 1 1]
 [1 1 1 1]]


In [14]:
#creating an array filled with constants
a4 = np.full((2,2), 7)
print("a14:" ,a4)

a14: [[7 7]
 [7 7]]


In [15]:
#creating a 2-D array with ones on diagonal and zeros elsewhere
a5 = np.eye(3)
print("a5:" ,a5)

a5: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#creating an array similar to number line
#linspace(startpoint, endpoint, number of items)
a6 = np.linspace(1,3,5)
print("a6 : ", a6)

a6 :  [1.  1.5 2.  2.5 3. ]


In [17]:
#creating an array using random function
np.array(np.random.randn(5), dtype='int')

array([1, 0, 0, 0, 0])

In [18]:
#creating an array with float type
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

In [19]:
#creating multi dimensional arrays
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
#converting 2D array into 1D
np.array([[2,3,4],[5,6,7]]).reshape(6,)

array([2, 3, 4, 5, 6, 7])

In [21]:
#creating 3D array
np.random.randn(24).reshape(2,3,4)

array([[[-1.42665707e-01, -1.15586478e+00,  7.46291254e-01,
          5.56803922e-03],
        [-1.44096677e+00,  1.23533997e-01,  1.38098939e+00,
          6.63980328e-02],
        [-5.17628613e-01,  8.84666372e-04,  1.98406935e-01,
         -3.51734460e-01]],

       [[ 9.41059824e-01, -1.96062923e-01,  8.58657364e-01,
          3.59181250e-01],
        [ 8.39633050e-01,  8.12500326e-02,  8.14122747e-02,
          1.73847044e-02],
        [ 3.94873201e-01,  1.21338185e+00, -1.18381767e+00,
         -3.14555564e-01]]])

### Indexing and Slicing

In [22]:
# Like Python lists, index starts at 0 for arrays as well. 
# array[startpoint, endpoint, increment]
i1 = np.arange(10,20).reshape(5,2)
print(i1)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [23]:
i1[1]

array([12, 13])

In [24]:
i1[1,1]

13

In [25]:
i1[1][1]

13

In [26]:
i1[2:4]

array([[14, 15],
       [16, 17]])

In [27]:
#slicing the internal array along with external array
i1[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [28]:
#slicing the internal array along with external array
i1[2:4, 1]

array([15, 17])

In [29]:
#slicing as per index number
i1[[0,2]]

array([[10, 11],
       [14, 15]])

In [30]:
#slicing as per index number and subsequent inner slicing
i1[[0,2],1]

array([11, 15])

In [31]:
x = np.arange(10,40,2).reshape(3,5)

In [32]:
for i in range(len(x)):
    print(x[[i],[1,3]])

[12 16]
[22 26]
[32 36]


In [33]:
np.array([x[[i],[1,3]] for i in range(len(x))])

array([[12, 16],
       [22, 26],
       [32, 36]])

### Boolean indexing

In [34]:
#return True or False for every element
i1 > 15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [35]:
#display elements as per condition
i1[i1>15]

array([16, 17, 18, 19])

In [36]:
#array of even numbers
i1[i1 % 2 == 0]

array([10, 12, 14, 16, 18])

### Vectorization

Vectorization is the ability of NumPy by which we can perform operations on entire arrays rather than on a single element.

In [37]:
#addition
x = np.array([1,2,4])
y = np.array([0,1,2])

In [38]:
x+10

array([11, 12, 14])

In [39]:
np.add(x,5)

array([6, 7, 9])

In [40]:
np.add(x,y)

array([1, 3, 6])

In [41]:
#subtraction
np.subtract(x,y)

array([1, 1, 2])

In [42]:
#multiplication
np.multiply(x,y)

array([0, 2, 8])

In [43]:
#division
np.divide(x, 2)

array([0.5, 1. , 2. ])

In [44]:
# Square root transformation
np.sqrt(x)

array([1.        , 1.41421356, 2.        ])

In [45]:
#Log transformation
np.log(x)

array([0.        , 0.69314718, 1.38629436])

### Aggregate Functions

In [46]:
y = np.arange(10,20).reshape(2,5)
print(y)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
#total sum of each items in the array
y.sum()

145

In [48]:
#column wise sum
y.sum(axis=0)

array([25, 27, 29, 31, 33])

In [49]:
#row wise sum
y.sum(axis=1)

array([60, 85])

In [50]:
#maximum of all
y.max()

19

In [51]:
#column wis max
y.max(axis=0)

array([15, 16, 17, 18, 19])

In [52]:
# row wise max
y.max(axis=1)

array([14, 19])

In [53]:
#minimum of all
y.min()

10

In [54]:
#mean
y.mean()

14.5

In [55]:
#median
np.median(y)

14.5

In [56]:
#variance
y.var()

8.25

In [57]:
#standard devation
np.std(y)

2.8722813232690143

### Math functions


In [58]:
np.sin(90)

0.8939966636005579

In [59]:
np.sqrt(144)

12.0

In [60]:
np.cos(90)

-0.4480736161291701

In [61]:
np.log(10)

2.302585092994046

In [62]:
np.log10(10)

1.0

### Array Comparision

In [63]:
np.array_equal(x,y)

False

### Broadcasting

In any dimension where one array had size 1 and the other array had a size greater than 1, the first array behaves as if it were copied along that dimension

In [64]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([2,3])

In [65]:
a1

array([[1, 2],
       [3, 4]])

In [66]:
a2

array([2, 3])

In [67]:
a1 + a2

array([[3, 5],
       [5, 7]])

### Cross product vs Dot product

In [68]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [69]:
a1

array([[1, 2],
       [3, 4]])

In [70]:
a2

array([[5, 6],
       [7, 8]])

In [71]:
#cross product
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [72]:
#dot product
np.dot(a1, a2)

array([[19, 22],
       [43, 50]])