#### What is NumPy?

It stands for "Numerical Python". NumPy is a Python module that provides fast and efficient array operations of homogeneous data. The central feature of NumPy is the array object class, also called the ndarray. Arrays are very similar to lists in Python, except that every element of an array must be of the same type (in lists you can hold data which have different types), typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

#### Creating NumPy arrays

The syntax of creating a NumPy array is:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

Here, the arguments

    object: Any object exposing the array interface
    dtype: Desired data type of array, optional
    copy: Optional. By default (true), the object is copied
    order: C (row major) or F (column major) or A (any) (default)
    subok: By default, returned array forced to be a base class array. If true, sub-classes passed through
    ndim: Specifies minimum dimensions of resultant array


In [1]:
#importing numpy library
import numpy as np

In [2]:
#creating 1D array
a = np.array([1,2,3,4])
#creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


### Attributes of numpy arrays

In [3]:
# Shape: returns a tuple consisting of array dimensions
print(a.shape)
print(b.shape)

(4,)
(2, 4)


In [4]:
#dimension: returns a number that describes no of dimesions of array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#Size: total number of items in the array
print(a.size)
print(b.size)

4
8


In [6]:
#Datatype: name of the datatype that is stored in array
print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
#itemsize: the memory consumed by the array
print(a.itemsize)
print(b.itemsize)

4
4


In [8]:
#creating an array of 1st 10 natural numbers
#please note arange function of numpy is similar to range function in python
#arange(startpoint=0, endpoint, increment=1)
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Changing the shape of the array, basically changing the dimension of the array
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
lst = [1,2.3, "abc", True]
y = np.array(lst)
print(y)

['1' '2.3' 'abc' 'True']


### Techniques of creating arrays

In [11]:
#1. creating an empty array
a1 = np.empty((3,2), dtype='int32')
print("a1:" ,a1)


a1: [[-132167920        552]
 [         0          0]
 [    131074          0]]


In [12]:
# creating an array with all zeroes
a2 = np.zeros((3,4), dtype='int32')
print("a2:" ,a2)


a2: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
#creating an array with all ones
a3 = np.ones((2,4), dtype="int32")
print("a3:" ,a3)

a3: [[1 1 1 1]
 [1 1 1 1]]


In [14]:
#creating an array filled with constants
a4 = np.full((2,2), 7)
print("a14:" ,a4)

a14: [[7 7]
 [7 7]]


In [15]:
#creating a 2-D array with ones on diagonal and zeros elsewhere
a5 = np.eye(3)
print("a5:" ,a5)

a5: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#creating an array similar to number line
#linspace(startpoint, endpoint, number of items)
a6 = np.linspace(1,3,5)
print("a6 : ", a6)

a6 :  [1.  1.5 2.  2.5 3. ]


In [17]:
#creating an array using random function
np.array(np.random.randn(5), dtype='int')

array([0, 0, 1, 0, 0])

In [18]:
#creating an array with float type
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

In [19]:
#creating multi dimensional arrays
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
#converting 2D array into 1D
np.array([[2,3,4],[5,6,7]]).reshape(6,)

array([2, 3, 4, 5, 6, 7])

In [21]:
#creating 3D array
np.random.randn(24).reshape(2,3,4)

array([[[-1.07279263, -0.76805613, -0.37356578, -1.68344661],
        [-1.44795354,  0.36478071, -1.5267491 ,  0.20208719],
        [ 0.31590637,  0.50107763, -0.70458885,  0.13222723]],

       [[ 1.49203166,  0.62631007,  0.27093184, -0.55445256],
        [-0.11998188,  1.13103038,  1.09694065,  0.33171745],
        [-0.93680393, -1.92143493, -0.34652042, -1.13419186]]])

### Indexing and Slicing

In [22]:
# Like Python lists, index starts at 0 for arrays as well. 
# array[startpoint, endpoint, increment]
i1 = np.arange(10,20).reshape(5,2)
print(i1)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [23]:
i1[1]

array([12, 13])

In [24]:
i1[1,1]

13

In [25]:
i1[1][1]

13

In [26]:
i1[2:4]

array([[14, 15],
       [16, 17]])

In [27]:
#slicing the internal array along with external array
i1[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [28]:
#slicing the internal array along with external array
i1[2:4, 1]

array([15, 17])

In [29]:
#slicing as per index number
i1[[0,2]]

array([[10, 11],
       [14, 15]])

In [30]:
#slicing as per index number and subsequent inner slicing
i1[[0,2],1]

array([11, 15])

In [31]:
x = np.arange(10,40,2).reshape(3,5)

In [32]:
for i in range(len(x)):
    print(x[[i],[1,3]])

[12 16]
[22 26]
[32 36]


In [33]:
np.array([x[[i],[1,3]] for i in range(len(x))])

array([[12, 16],
       [22, 26],
       [32, 36]])

### Boolean indexing

In [34]:
#return True or False for every element
i1 > 15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [35]:
#display elements as per condition
i1[i1>15]

array([16, 17, 18, 19])

In [36]:
#array of even numbers
i1[i1 % 2 == 0]

array([10, 12, 14, 16, 18])

### Vectorization

Vectorization is the ability of NumPy by which we can perform operations on entire arrays rather than on a single element.

In [37]:
#addition
x = np.array([1,2,4])
y = np.array([0,1,2])

In [38]:
x+10

array([11, 12, 14])

In [39]:
np.add(x,5)

array([6, 7, 9])

In [40]:
np.add(x,y)

array([1, 3, 6])

In [41]:
#subtraction
np.subtract(x,y)

array([1, 1, 2])

In [42]:
#multiplication
np.multiply(x,y)

array([0, 2, 8])

In [43]:
#division
np.divide(x, 2)

array([0.5, 1. , 2. ])

In [44]:
# Square root transformation
np.sqrt(x)

array([1.        , 1.41421356, 2.        ])

In [45]:
#Log transformation
np.log(x)

array([0.        , 0.69314718, 1.38629436])

### Aggregate Functions

In [46]:
y = np.arange(10,20).reshape(2,5)
print(y)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
#total sum of each items in the array
y.sum()

145

In [48]:
#column wise sum
y.sum(axis=0)

array([25, 27, 29, 31, 33])

In [49]:
#row wise sum
y.sum(axis=1)

array([60, 85])

In [50]:
#maximum of all
y.max()

19

In [51]:
#column wis max
y.max(axis=0)

array([15, 16, 17, 18, 19])

In [52]:
# row wise max
y.max(axis=1)

array([14, 19])

In [53]:
#minimum of all
y.min()

10

In [54]:
#mean
y.mean()

14.5

In [55]:
#median
np.median(y)

14.5

In [56]:
#variance
y.var()

8.25

In [57]:
#standard devation
np.std(y)

2.8722813232690143

### Math functions


In [58]:
np.sin(90)

0.8939966636005579

In [59]:
np.sqrt(144)

12.0

In [60]:
np.cos(90)

-0.4480736161291701

In [61]:
np.log(10)

2.302585092994046

In [62]:
np.log10(10)

1.0

### Array Comparision

In [63]:
np.array_equal(x,y)

False

### Broadcasting

In any dimension where one array had size 1 and the other array had a size greater than 1, the first array behaves as if it were copied along that dimension

In [64]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([2,3])

In [65]:
a1

array([[1, 2],
       [3, 4]])

In [66]:
a2

array([2, 3])

In [67]:
a1 + a2

array([[3, 5],
       [5, 7]])

### Cross product vs Dot product

In [68]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [69]:
a1

array([[1, 2],
       [3, 4]])

In [70]:
a2

array([[5, 6],
       [7, 8]])

In [71]:
#cross product
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [72]:
#dot product
np.dot(a1, a2)

array([[19, 22],
       [43, 50]])

###  IQR, lower whisker and upper whisker using numpy

https://drive.google.com/open?id=1Kp1wACkgsFzHrU1GjJ9YzxI4vodtzOjz

In [73]:
a = np.array([1,1,2,2,2,2,2,3,3,3,4,4,5,6,7,8,9, 15, 20])

In [74]:
a

array([ 1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  4,  4,  5,  6,  7,  8,  9,
       15, 20])

In [75]:
np.mean(a)

5.2105263157894735

In [76]:
np.median(a)

3.0

In [77]:
# calculating quantile at 25%
q1 = np.quantile(a, 0.25)

In [78]:
q1

2.0

In [79]:
# calculation quantile at 75%
q3 = np.quantile(a, 0.75)

In [80]:
q3

6.5

In [81]:
iqr = q3-q1

In [82]:
iqr

4.5

In [83]:
lower_whisker = q1 - 1.5*iqr

In [84]:
lower_whisker

-4.75

In [85]:
upper_whisker = q3 + 1.5*iqr

In [86]:
upper_whisker

13.25

### Reducing Skewness

According to Wikipedia, "In probability theory and statistics, skewness is a measure of the asymmetry of the probability distribution of a real-valued random variable about its mean."

https://drive.google.com/file/d/1FXuLbFaJ5-TFfTfiFJHDBeAYT3CgyqaK/view?usp=sharing

    Normally skewed falls in the range -0.5 to 0.5
    Negatively skewed is < -0.5
    Positively skewed is > 0.5

In [87]:
x = np.array([1,2,2,3,3,3,4,4,16,20,25])

In [88]:
x

array([ 1,  2,  2,  3,  3,  3,  4,  4, 16, 20, 25])

In [89]:
np.mean(x)

7.545454545454546

In [90]:
np.median(x)

3.0

In [91]:
from scipy.stats import skew
skew(x)
# this data is positively skewed as the skew value > 0.5

1.1712731595847037

In [92]:
# Square root transformation
x1 = np.sqrt(x)

In [93]:
skew(x1)

0.9630668329521322

In [94]:
# Cube root transformation
x2 = np.cbrt(x)

In [95]:
skew(x2)

0.8614367405966747

In [96]:
#log transformation
x3 = np.log(x)

In [97]:
skew(x3)

0.5583822828505749

### More functions

In [98]:
#The copy function can be used to create a new, separate copy of an array in memory if needed
a=np.array([1,2,3])

In [99]:
a

array([1, 2, 3])

In [100]:
b=a

In [101]:
b

array([1, 2, 3])

In [106]:
a[0] = 100

In [107]:
a

array([100,   2,   3])

In [108]:
b

array([100,   2,   3])

In [109]:
c = a.copy()

In [110]:
a[0] = 1000

In [111]:
a

array([1000,    2,    3])

In [112]:
b

array([1000,    2,    3])

In [113]:
c

array([100,   2,   3])

In [114]:
#Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched: 
y = np.arange(10,20).reshape(2,5)
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
y.transpose()

array([[10, 15],
       [11, 16],
       [12, 17],
       [13, 18],
       [14, 19]])

In [116]:
#One-dimensional versions of multi-dimensional arrays can be generated with flatten
y.flatten()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [117]:
# Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined
a = np.array([1,2])
b = np.array([3,4,5])
c = np.array([5,6,7])
#concatenate works with same dimension
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 5, 6, 7])

In [118]:
#If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated.
#By default (without specifying the axis), NumPy concatenate along the first dimension:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [119]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [120]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])