#### What is NumPy?

It stands for "Numerical Python". NumPy is a Python module that provides fast and efficient array operations of homogeneous data. The central feature of NumPy is the array object class, also called the ndarray. Arrays are very similar to lists in Python, except that every element of an array must be of the same type (in lists you can hold data which have different types), typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

#### Creating NumPy arrays

The syntax of creating a NumPy array is:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

Here, the arguments

    object: Any object exposing the array interface
    dtype: Desired data type of array, optional
    copy: Optional. By default (true), the object is copied
    order: C (row major) or F (column major) or A (any) (default)
    subok: By default, returned array forced to be a base class array. If true, sub-classes passed through
    ndim: Specifies minimum dimensions of resultant array


In [1]:
#importing numpy library
import numpy as np

In [2]:
#creating 1D array
a = np.array([1,2,3,4])
#creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
#Attributes of numpy arrays
# Shape: returns a tuple consisting of array dimensions
print(a.shape)
print(b.shape)

(4,)
(2, 4)


In [4]:
#dimension: returns a number that describes no of dimesions of array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#Size: total number of items in the array
print(a.size)
print(b.size)

4
8


In [6]:
#Datatype: name of the datatype that is stored in array
print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
#itemsize: the memory consumed by the array
print(a.itemsize)
print(b.itemsize)

4
4


In [8]:
#creating an array of 1st 10 natural numbers
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Changing the shape of the array, basically changing the dimension of the array
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
lst = [1,2.3, "abc", True]
y = np.array(lst)
print(y)

['1' '2.3' 'abc' 'True']
